### PR TITLE
Stop hosting large PDF files in git repo

### PR DESCRIPTION
**Pull request by patcon**
We can currently access the doc for direct download here:
https://drive.google.com/uc?export=download&id=0B7JMg0M6gVfjb3BUanlBMjRkNWM

Might we be able to commit to maintaining that link, and point there instead of hosting large files in git? (repo is currently 50MB+, and grows every time we add/change a file)

Also, in investigating #29, it struck me that we can easily host on free app instance, but the bandwidth might add up on heroku. Google Drive bandwidth is free (yay!)

### CODE REVIEW

**Comment by dcwalk** [comment]
@patcon -- the PDF is already hosted on envirodatagov.org (https://envirodatagov.org/wp-content/uploads/2017/06/Part-1-EPA-Under-Siege.pdf). I'd rather we use an 'EDGI' address rather than google drive.

But yes, fully support pulling it out of the repo.

**Comment by patcon** [comment]
ok perf.

one concern, since i'm not familiar with how wordpress works: what happens when someone uploads a new version to wordpress? does it manage "versions" and so we just get the update at the same link, or will we go into jekyll site and update?

**Comment by dcwalk** [comment]
WordPress supports both: 
- you can re-upload over the same file path (e.g., anchor to to above always)
- you can upload a new one and it'll be bucketed by year/month
We'll just have to be careful how any updates are managed.

That said, appropriate version tracking should be maintained in the gdrive (e.g. having side by side all versions of the report).

**Comment by dcwalk** [comment]
I've only ever pruned and filtered branches on github sporadically before. IIRC a bit arcane, lemme know if you need anything!

**Comment by patcon** [comment]
@dcwalk good call, but perhaps I'll just mark that as a post-task after merging this. It involves a force-push and history rewrite, so it's not something pull-requestable that fits here.

If you felt like giving it a +1, I'm happy to do the pruning after merge

**Comment by patcon** [comment]
Actually, going to wait until other PRs are merged, or they'll be messy

**Pull request merged**
