### PR TITLE
simplified

### PR DESCRIPTION
**Pull request by shaqsingh**

### CODE REVIEW

**Review by titaniumbones — COMMENTED** [review]
I haven't been following much s I'm not sure my review is so helpful... 

- EDGI logo makes sense but probably we want some kind of a cover image as well?
- new metadata seems sensible.  Not sure why moving from .md to .html... 

Basically I don't think my review's very helpful! But happy to respond further if that seems helpful.

**Comment by patcon** [comment]
[redacted] was looking at master. Sorry!

**Comment by patcon** [comment]
For future reference, a feature branch would be helpful for local reviews. (when doing direct on `master`, reviewer needd to git-fu to track to a different branch like `shaqsingh-master` or whatevs :)

**Review by patcon — APPROVED** [review]
LGTM! merge away

**Comment by patcon** [comment]
> EDGI logo makes sense but probably we want some kind of a cover image as well?

Sorry, just saw this :P Would it make sense for that to be a new ticket @titaniumbones? This seems functional and would get us some place beyond this http://100days.envirodatagov.org/

>  Not sure why moving from .md to .html...

As I discovered in my redacted comment, MD results in this:

screenshot

**Comment by patcon** [comment]
I think @titaniumbones is in the wilderness, so reticketed the suggestion to move things along :)

**Pull request merged**
