### PR TITLE
Bugz

### PR DESCRIPTION
**Pull request by shaqsingh**
layout fixes

### CODE REVIEW

**Comment by dcwalk** [comment]
Hey @shaqsingh this PR was not off the most current commit in master, are you able to rebase?
I'm seeing some issues that were fixed in #56 that will be reintroduced if this is merged in

**Comment by shaqsingh** [comment]
@dcwalk just fixed conflicts

**Comment by shaqsingh** [comment]
@dcwalk wait just rebased....anddd it didn't work

**Comment by shaqsingh** [comment]
ok this is a good place to reploy at @dcwalk

**Comment by shaqsingh** [comment]
ok i think it rebased correctly @dcwalk

**Comment by dcwalk** [comment]
Okay I'm deploying, @shaqsingh can you start off master for the next PR?

**Pull request merged**
